### PR TITLE
feat(scw-timings): added support for changing sc widget timing via timestamp links

### LINKED ISSUE #5: Timeout navigation support for soundcloud widget in shownotes
image

### PR DESCRIPTION
**Pull request by eugrdn**
Closes #5

### CODE REVIEW

**Comment by eugrdn** [comment]
Wyt guys? I could change other posts if this solution suits you

**Comment by ovr** [comment]
Hey!

WoW! You did a great job, thank you!

P.S Sorry for late reply 😄

**Comment by eugrdn** [comment]
You welcome!

**Comment by eugrdn** [comment]
ps you need to add timings for other posts as well

**Comment by ovr** [comment]
> ps you need to add timings for other posts as well

Already did it in https://github.com/underjs/underjs.ru/commit/f5ee719fc124425dbd3fe1786b5fea4234b91dcb

**Pull request merged**
